language: csharp
solution: LargeList.sln

env:
  global:
    - secure: $COVERITY_SCAN_TOKEN

addons:
  coverity_scan:
    project:
      name: "dlebansais/LargeList"
      description: "LargeList"

    notification_email: $NOTIFICATION_EMAIL
    build_command_prepend: "cov-configure --template --compiler csc.exe --comptype csc"
    build_command: /usr/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x64 /errorreport:prompt /define:DEBUG /highentropyva+ /reference:/usr/lib/mono/4.5.2-api/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5.2-api/mscorlib.dll /reference:/usr/lib/mono/4.5.2-api/System.Core.dll /reference:/usr/lib/mono/4.5.2-api/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.5.2-api/System.Data.dll /reference:/usr/lib/mono/4.5.2-api/System.dll /reference:/usr/lib/mono/4.5.2-api/System.Net.Http.dll /reference:/usr/lib/mono/4.5.2-api/System.Xml.dll /reference:/usr/lib/mono/4.5.2-api/System.Xml.Linq.dll /filealign:512 /optimize+ /out:LargeList/obj/x64/Travis/LargeList.dll /subsystemversion:6.00 /target:library /utf8output LargeList/EnumerableSegmentTable.cs LargeList/GlobalSuppressions.cs LargeList/LargeCollection.cs LargeList/LargeCollectionDebugView.cs LargeList/LargeList.cs LargeList/LargeListAssemblyAttribute.cs LargeList/PartitionAlgorithmCommands.cs LargeList/PartitionAlgorithmQueries.cs LargeList/PartitionEnumerator.cs LargeList/Properties/AssemblyInfo.cs LargeList/ReadOnlyLargeCollection.cs LargeList/ReadOnlyLargeList.cs LargeList/Segment.cs LargeList/Partition.cs
    branch_pattern: coverity-scan

install:
- nuget restore LargeList.sln
- nuget install NUnit -Version 3.12.0 -OutputDirectory test-runner
- nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory test-runner
- mkdir -p /home/travis/build/dlebansais/LargeList/LargeList/obj/x64/Travis
- mkdir -p /home/travis/build/dlebansais/LargeList/LargeList/bin/x64/Travis

script:
#- msbuild /p:Configuration=Travis LargeList.sln
- ls /home/travis/build/dlebansais/LargeList/LargeList/obj/x64/Travis
- ls /home/travis/build/dlebansais/LargeList/LargeList/bin/x64/Travis
- cat /home/travis/build/dlebansais/LargeList/cov-int/build-log.txt
- cp ./test-runner/NUnit.3.12.0/lib/net45/nunit.framework.dll ./LargeList/bin/x64/Travis/
- mono ./test-runner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --trace=Debug --labels=All ./LargeList/bin/x64/Travis/Test-LargeList.dll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./LargeList/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master
