language: csharp
solution: LargeList.sln

env:
  global:
    - secure: $COVERITY_SCAN_TOKEN

addons:
  coverity_scan:
    project:
      name: "dlebansais/LargeList"
      description: "LargeList is an implementation of Collection<> and List<> that can hold a number of elements limited only by the available memory, tested up to 8 billions."

    notification_email: dlebansais@gmail.com
    build_command_prepend: ./configure
    build_command: msbuild /p:Configuration=Travis LargeList.sln
    branch_pattern: coverity-scan

install:
- nuget restore LargeList.sln
- nuget install NUnit -Version 3.12.0 -OutputDirectory test-runner
- nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory test-runner

script:
- msbuild /p:Configuration=Travis LargeList.sln
- cp ./test-runner/NUnit.3.12.0/lib/net45/nunit.framework.dll ./LargeList/bin/x64/Release/
- mono ./test-runner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --trace=Debug --labels=All ./LargeList/bin/x64/Release/Test-LargeList.dll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./LargeList/bin/x64/Release
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master
