language: csharp
solution: LargeList.sln

env:
  global:
    - secure: $COVERITY_SCAN_TOKEN

addons:
  coverity_scan:
    project:
      name: "dlebansais/LargeList"
      description: "LargeList"

    notification_email: $NOTIFICATION_EMAIL
#    build_command_prepend: "cov-configure --template --compiler csc.exe --comptype csc"
#    build_command: msbuild /p:Configuration=Travis
#    branch_pattern: coverity-scan
    build_command_prepend: msbuild /t:Clean
    build_command: /usr/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x64 /errorreport:prompt /define:DEBUG /highentropyva+ /reference:/usr/lib/mono/4.5.2-api/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5.2-api/mscorlib.dll /reference:/usr/lib/mono/4.5.2-api/System.Core.dll /reference:/usr/lib/mono/4.5.2-api/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/4.5.2-api/System.Data.dll /reference:/usr/lib/mono/4.5.2-api/System.dll /reference:/usr/lib/mono/4.5.2-api/System.Net.Http.dll /reference:/usr/lib/mono/4.5.2-api/System.Xml.dll /reference:/usr/lib/mono/4.5.2-api/System.Xml.Linq.dll /filealign:512 /optimize+ /out:obj/x64/Travis/LargeList.dll /subsystemversion:6.00 /target:library /utf8output /analyzer:../packages/StyleCop.Analyzers.1.1.118/analyzers/dotnet/cs/StyleCop.Analyzers.CodeFixes.dll /analyzer:../packages/StyleCop.Analyzers.1.1.118/analyzers/dotnet/cs/StyleCop.Analyzers.dll EnumerableSegmentTable.cs GlobalSuppressions.cs LargeCollection.cs LargeCollectionDebugView.cs LargeList.cs LargeListAssemblyAttribute.cs PartitionAlgorithmCommands.cs PartitionAlgorithmQueries.cs PartitionEnumerator.cs Properties/AssemblyInfo.cs ReadOnlyLargeCollection.cs ReadOnlyLargeList.cs Segment.cs Partition.cs 
    branch_pattern: coverity-scan

install:
- nuget restore LargeList.sln
- nuget install NUnit -Version 3.12.0 -OutputDirectory test-runner
- nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory test-runner

script:
#- msbuild /p:Configuration=Travis LargeList.sln
- cat /home/travis/build/dlebansais/LargeList/cov-int/build-log.txt
- cp ./test-runner/NUnit.3.12.0/lib/net45/nunit.framework.dll ./LargeList/bin/x64/Travis/
- mono ./test-runner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --trace=Debug --labels=All ./LargeList/bin/x64/Travis/Test-LargeList.dll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./LargeList/bin/x64/Travis
  target_branch: gh-pages
  email: "github-pages-deploy@travis-ci.org"
  on:
    branch: master
