<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net481;net10.0</TargetFrameworks>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <Platforms>x64</Platforms>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version>1.2.0</Version>
        <Authors>David Le Bansais</Authors>
        <Company />
        <Product />
        <Description>An implementation of Collection&lt;&gt; and List&lt;&gt; that can hold a number of elements limited only by the available memory, tested up to 8 billions</Description>
        <Copyright>Copyright © 2026 David Le Bansais</Copyright>
        <AssemblyVersion>1.2.0.372</AssemblyVersion>
        <FileVersion>1.2.0.372</FileVersion>
        <RepositoryUrl>https://github.com/dlebansais/LargeList</RepositoryUrl>
        <RootNamespace>LargeList</RootNamespace>
        <NeutralLanguage>en-US</NeutralLanguage>
        <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
        
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>

        <PackageLicenseExpression>0BSD</PackageLicenseExpression>
        <PackageIcon>package-icon.png</PackageIcon>
        <PackageReadmeFile>README-short.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(ENABLE_STRICT)'=='true'">
        <DefineConstants>$(DefineConstants);STRICT</DefineConstants>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="..\.editorconfig" Link=".editorconfig" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.IDisposableAnalyzers" Version="4.0.8.17">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.CSharpLatest" Version="2.7.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="PolySharp" Version="1.16.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.Method.Contracts.Analyzers-Debug" Version="2.0.10" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="dlebansais.Method.Contracts.Analyzers" Version="2.0.10" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="dlebansais.Method.Contracts-Debug" Version="2.0.7" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
        <PackageReference Include="dlebansais.Method.Contracts" Version="2.0.7" Condition="'$(Configuration)|$(Platform)'!='Debug|x64'" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SolutionDir)'!='*Undefined*' And '$(ENABLE_STRICT)'==''">
        <Exec Command="if exist &quot;$(SolutionDir)updatecommit.bat&quot; call &quot;$(SolutionDir)updatecommit.bat&quot; &quot;$(SolutionDir)&quot; &quot;$(TargetPath)&quot;" />
        <Exec Command="if exist &quot;$(SolutionDir)signfile.bat&quot; call &quot;$(SolutionDir)signfile.bat&quot; &quot;$(SolutionDir)&quot; &quot;$(Configuration)-$(Platform)&quot; &quot;$(TargetPath)&quot;" Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />

        <ItemGroup>
            <None Remove="@(None)" />
        </ItemGroup>

        <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
            <None Include="$(TargetDir)$(ProjectName).dll" />
            <None Include="$(TargetDir)$(ProjectName).pdb" />
            <None Include="$(TargetDir)$(ProjectName).xml" />
        </ItemGroup>
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget-debug\lib\$(TargetFramework)\" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
        <Copy SourceFiles="package-icon.png" DestinationFolder="$(SolutionDir)nuget-debug\" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />
        <Copy SourceFiles="README-short.md" DestinationFolder="$(SolutionDir)nuget-debug\" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" />

        <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
            <None Include="$(TargetDir)$(ProjectName).dll" />
            <None Include="$(TargetDir)$(ProjectName).xml" />
        </ItemGroup>
        <Copy SourceFiles="@(None)" DestinationFolder="$(SolutionDir)nuget\lib\$(TargetFramework)\" Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />
        <Copy SourceFiles="package-icon.png" DestinationFolder="$(SolutionDir)nuget\" Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />
        <Copy SourceFiles="README-short.md" DestinationFolder="$(SolutionDir)nuget\" Condition="'$(Configuration)|$(Platform)'=='Release|x64'" />
    </Target>

</Project>
